### Localhost testing
### Get all
GET http://localhost:3001/api/persons

### Get Valid person
GET http://localhost:3001/api/persons/6059c3721d21303a1b5bb7b6

### get Invalid person
GET http://localhost:3001/api/persons/1000

### Delete valid/already deleted person
DELETE http://localhost:3001/api/persons/6059c3721d21303a1b5bb7b6

### New person // Already exits(send twice)
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "sample person",
    "number": "123 456 7896"
}

### number missing
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "sample4"
}
