### Get all
GET http://localhost:3001/api/persons

### Get Valid person
GET http://localhost:3001/api/persons/1

### get Invalid person
GET http://localhost:3001/api/persons/1000

### Delete valid person
DELETE http://localhost:3001/api/persons/1

### Delete invalid person
DELETE http://localhost:3001/api/persons/1000

### New person // Already exits(send twice)
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "sample4",
    "number": "123 456 7896"
}

### number missing
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "sample4"
}